require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "c",
    "go",
    "lua",
    "css",
    "vim",
    "php",
    "xml",
    "json",
    "html",
    "toml",
    "bash",
    "rust",
    "toml",
    "yaml",
    "java",
    "ruby",
    "rust",
    "http",
    "regex",
    "query",
    "python",
    "vimdoc",
    "graphql",
    "comment",
    "dockerfile",
    "javascript",
    "typescript",
  },

  auto_install = true,
  highlight = { enable = true, },
  indent = { enable = true },
  folding = { enable = false },
  textobjects = {
    select = {
      enable = false,
    },
  },
}
