unbind r
bind r source-file ~/.tmux.conf

# prefix
set -g prefix C-w
set -g escape-time 0
set -ga terminal-overrides ",xterm-256color:Tc"
set -g status-position top
set-option -g focus-events on

#Vim like pane switching
set -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key x kill-window

# Spilting windows
bind-key p split-window -h
bind-key b split-window -v
# set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'christoomey/vim-tmux-navigator' 

# tmux sessions manager
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '2'
# set -g @continuum-boot 'on'
# set -g status-right 'Continuum status: #{continuum_status}'

# nvim state restore
set -g @resurrect-strategy-nvim 'session'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
